# arlatex
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/arlatex.1
complete -c arlatex -l version --description 'Output the arlatex script\'s version number.'
complete -c arlatex -l help --description 'Output brief arlatex usage information.'
complete -c arlatex -l document --description 'Specify the master document.'

