# avsbufplay
# Autogenerated from man page /usr/share/man/man1/avsbufplay.1
complete -c avsbufplay -s a --description 'Description of -a flag.'
complete -c avsbufplay -s b --description 'Description of -b flag \\" Ends the list Pp .'

