# bbox
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/bbox.1
complete -c bbox -s h -l help --description 'Show summary of options.'
complete -c bbox -s V --description 'Show version of program.'
complete -c bbox -s r --description 'resolution of picture in dpi.'

