# bibdoiadd
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/bibdoiadd.1
complete -c bibdoiadd -s c --description 'Configuration file.   If this file is absent, some defaults are used.'

