# cbc-n1qlback
# Autogenerated from man page /usr/local/share/man/man1/cbc-n1qlback.1
complete -c cbc-n1qlback -s f -l queryfile --description 'Path to a file containing the query bodies to execute in JSON format, one que…'
complete -c cbc-n1qlback -s t -l num-threads --description 'Set the number of threads (and thus the number of client instances) to run co…'
complete -c cbc-n1qlback -s U -l spec --description 'A string describing the cluster to connect to.'
complete -c cbc-n1qlback -s u -l username --description 'Specify the username for the bucket.  As of Couchbase Server 2.'
complete -c cbc-n1qlback -s P -l password --description '.'
complete -c cbc-n1qlback -s T -l timings --description 'Dump command timings at the end of execution.'
complete -c cbc-n1qlback -s v -l verbose --description 'Specify more information to standard error about what the client is doing.'

