# cbc
# Autogenerated from man page /usr/local/share/man/man1/cbc.1
complete -c cbc -s U -l spec --description 'A string describing the cluster to connect to.'
complete -c cbc -s u -l username --description 'Specify the username for the bucket.  As of Couchbase Server 2.'
complete -c cbc -s P -l password --description '.'
complete -c cbc -s T -l timings --description 'Dump command timings at the end of execution.'
complete -c cbc -s v -l verbose --description 'Specify more information to standard error about what the client is doing.'

