# corespeech_tool
# Autogenerated from man page /usr/share/man/man1/corespeech_tool.1
complete -c corespeech_tool -s a --description 'Description of -a flag.'
complete -c corespeech_tool -s b --description 'Description of -b flag \\" Ends the list Pp .'

