# ctanify
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/ctanify.1
complete -c ctanify -s h -l help --description 'Output basic usage information and exit.'
complete -c ctanify -s V -l version --description 'Output ctanify\'s version number and exit.'
complete -c ctanify -s p -l pkgname --description 'Specify explicitly a package name.'
complete -c ctanify -l noauto --description 'Do not automatically add files to the tarball.'

