# ctie
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/ctie.1
complete -c ctie -s c --description 'Create a single change file from the given R changefile s.'
complete -c ctie -s m --description 'Create a new master file by applying the given changefile s.'

