# dbsessmgr
# Autogenerated from man page /usr/local/share/man/man1/dbsessmgr.1
complete -c dbsessmgr -l clean --description 'Remove all expired sessions.'
complete -c dbsessmgr -l remove --description 'Delete all sessions.'
complete -c dbsessmgr -l show --description 'Display session data.'

