# detex
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/detex.1
complete -c detex -s n --description 'option is used, no \\input or \\include commands will be processed.'
complete -c detex -s l --description 'option can be used to force LaTeX mode and the.'
complete -c detex -s t --description 'option can be used to force TeX mode regardless of input content.'
complete -c detex -s e --description 'option can be used to specify a comma separated environment-list of environme…'
complete -c detex -s c --description 'option can be used in LaTeX mode to have detex echo the arguments to \\cite, \\…'
complete -c detex -s w --description 'flag is given, the output is a word list, one `word\' (string of two or more l…'
complete -c detex -s s --description 'option.'

