# dt2dv
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/dt2dv.1
complete -c dt2dv -o group --description 'Expect each DTL command to be in parentheses.'
complete -c dt2dv -o si --description 'Read all DTL commands from standard input.'
complete -c dt2dv -o debug --description 'Turn on detailed debugging output.'
complete -c dt2dv -o so --description 'Write all DVI commands to standard output.'

