# dvi2fax
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/dvi2fax.1
complete -c dvi2fax -o hi --description 'use high fax resolution (204x196 dpi) (default).'
complete -c dvi2fax -o lo --description 'use low fax resolution (204x98).'

