# dvibook
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/dvibook.1
complete -c dvibook -s s --description 'option selects the size of signature which will be used.'
complete -c dvibook -s q --description 'option suppresses this.'

