# dvicopy
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/dvicopy.1
complete -c dvicopy -o magnification --description 'Override existing magnification with R NUMBER . PP.'
complete -c dvicopy -o max-pages --description 'Process  NUMBER pages; default one million. PP.'
complete -c dvicopy -o page-start --description 'Start at PAGE-SPEC , for example `2\' or `5. *. -2\'.'

