# dvired
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/dvired.1
complete -c dvired -s o --description '.'
complete -c dvired -s P --description '.'
complete -c dvired -s f --description '.'

