# dvitomp
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/dvitomp.1
complete -c dvitomp -o help --description 'write usage summary and exit.'
complete -c dvitomp -o version --description 'output version information and exit.'

