# dvitodvi
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/dvitodvi.1
complete -c dvitodvi -s w --description 'option gives the width which is used by the w dimension specifier, and the.'
complete -c dvitodvi -s h --description 'option gives the height which is used by the h dimension specifier.'
complete -c dvitodvi -s q --description 'option suppresses this.'

