# extractbb
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/extractbb.1
complete -c extractbb -s v --description 'Be verbose.'
complete -c extractbb -s q --description 'Be quiet.'
complete -c extractbb -s O --description 'Write output to standard output.'
complete -c extractbb -s m --description 'Write output in dvipdfm\'s ``bb\'\' format.'

