# extractres
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/extractres.1
complete -c extractres -s m --description 'option combines the resources of the same name into one file; this must be us…'

