# fc-cache
# Autogenerated from man page /usr/local/share/man/man1/fc-cache.1
complete -c fc-cache -s E --description 'Raise an error if there are no fonts in dir or directories in the configurati…'
complete -c fc-cache -s y --description 'Prepend dir to all paths for scanning.'

