# findhyph
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/findhyph.1
complete -c findhyph -s c --description 'display hyphenated words in context.'
complete -c findhyph -s f --description 'display font selectors and other strings starting with a backslash character.'
complete -c findhyph -s v --description 'display program version.'
complete -c findhyph -s p --description 'generate file containing information about one-letter prepositions and  conju…'

