# gftodvi
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/gftodvi.1
complete -c gftodvi -o overflow-label-offset --description 'specifies the distance from the right edge of the character bounding box at w…'
complete -c gftodvi -o verbose --description 'option, gftodvi operates silently.'

