# gftype
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/gftype.1
complete -c gftype -s i --description 'is given on the command line, and a symbolic listing of the gf commands, if.'
complete -c gftype -s m --description 'is specified.'

