# git-lfs-ls-files
# Autogenerated from man page /usr/local/share/man/man1/git-lfs-ls-files.1
complete -c git-lfs-ls-files -s l -l long --description 'Show the entire 64 character OID, instead of just first 10.'

