# koi8rxterm
# Autogenerated from man page /opt/X11/share/man/man1/koi8rxterm.1
complete -c koi8rxterm -o class --description 'and.'
complete -c koi8rxterm -o k8 --description 'options should not be specified because they are used by the wrapper.'

