# kpsereadlink
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/kpsereadlink.1
complete -c kpsereadlink -l help --description 'Print help message and exit.'
complete -c kpsereadlink -l version --description 'Print version information and exit.'

