# kpseaccess
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/kpseaccess.1
complete -c kpseaccess -l help --description 'Print help message and exit.'
complete -c kpseaccess -l version --description 'Print version information and exit.'

