# kpsestat
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/kpsestat.1
complete -c kpsestat -l help --description 'Print help message and exit.'
complete -c kpsestat -l version --description 'Print version information and exit.'

