# latexdiff-vc
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/latexdiff-vc.1
complete -c latexdiff-vc -l rcs -l svn -l cvs -l git -l hg --description 'Set the version system.'
complete -c latexdiff-vc -s r -s r -l revision -l revision --description 'Choose revision (under \\s-1RCS\\s0, \\s-1CVS\\s0, \\s-1SVN\\s0, \\s-1GIT\\s0 or \\s-1…'
complete -c latexdiff-vc -s d -l dir -s d -l dir --description 'Rather than appending the string \\f(CW\\*(C`diff\\*(C\' and optionally the versi…'
complete -c latexdiff-vc -l flatten -l flatten --description 'If combined with \\f(CW\\*(C`--git\\*(C\', \\f(CW\\*(C`--svn\\*(C\' or \\f(CW\\*(C`--hg…'
complete -c latexdiff-vc -l fast -l so --description 'Use \\f(CW\\*(C`latexdiff-fast\\*(C\' or \\f(CW\\*(C`latexdiff-so\\*(C\', respectivel…'
complete -c latexdiff-vc -l ps -l postscript --description 'Generate postscript output from difference file.'
complete -c latexdiff-vc -l pdf --description 'Generate pdf output from difference file using \\f(CW\\*(C`pdflatex\\*(C\'.'
complete -c latexdiff-vc -l only-changes --description 'Post-process the output such that only pages with changes on them are display…'
complete -c latexdiff-vc -l force --description 'Overwrite existing diff files without asking for confirmation.'
complete -c latexdiff-vc -l help -s h --description 'Show help text.'

