# ltx2crossrefxml
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/ltx2crossrefxml.1
complete -c ltx2crossrefxml -s c --description 'Configuration file.   If this file is absent, some defaults are used.'

