# mdoc-export-msxdoc
# Autogenerated from man page /usr/local/share/man/man1/mdoc-export-msxdoc.1
complete -c mdoc-export-msxdoc -s o -l out --description 'The XML file to generate.'
complete -c mdoc-export-msxdoc -s h -s '?' -l help --description 'Display a help message and exit.  MAILING LISTS.'

