# mdoc-validate
# Autogenerated from man page /usr/local/share/man/man1/mdoc-validate.1
complete -c mdoc-validate -l format --description 'The documentation format to validate PATHS against.'
complete -c mdoc-validate -s h -s '?' -l help --description 'Display a help message and exit.'

