# mktextfm
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mktextfm.1
complete -c mktextfm -l destdir --description 'A directory name.  If the directory is absolute, it is used as-is.'
complete -c mktextfm -l help --description 'Print help message and exit.'
complete -c mktextfm -l version --description 'Print version information and exit.'

