# mktexlsr
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mktexlsr.1
complete -c mktexlsr -l help --description 'Print help message and exit.'
complete -c mktexlsr -l version --description 'Print version information and exit.'

