# mktexmf
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mktexmf.1
complete -c mktexmf -l help --description 'Print help message and exit.'
complete -c mktexmf -l version --description 'Print version information and exit.'

