# mono-api-info
# Autogenerated from man page /usr/local/share/man/man1/mono-api-info.1
complete -c mono-api-info -l abi --description 'Show the ABI instead of the API, that is, non-static fields (even the non-pub…'

