# mpost
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mpost.1
complete -c mpost -l ini --description 'option is given, preloading does not happen.'
complete -c mpost -l dvitomp --description 'option is given,  acts as DVI-to-MPX converter only.'

