# mptopdf
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mptopdf.1
complete -c mptopdf -l metafun --description 'use the metafun format to process the file (default is mpost).'
complete -c mptopdf -l texexec --description 'use texexec (context) to process text snippets.'
complete -c mptopdf -l latex --description 'use latex to process text snippets AUTHOR More information about ConTeXt and …'

