# mtx-colors
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-colors.1
complete -c mtx-colors -l table --description 'show icc table AUTHOR More information about ConTeXt and the tools that come …'

