# mtx-grep
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-grep.1
complete -c mtx-grep -l pattern --description 'search for pattern (optional).'
complete -c mtx-grep -l count --description 'count matches only.'
complete -c mtx-grep -l nocomment --description 'skip lines that start with %% or #.'
complete -c mtx-grep -l xml --description 'pattern is lpath expression AUTHOR More information about ConTeXt and the too…'

