# mtx-package
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-package.1
complete -c mtx-package -l merge --description 'merge \'loadmodule\' into merge file AUTHOR More information about ConTeXt and …'

