# mtx-chars
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-chars.1
complete -c mtx-chars -l xtx --description 'generate xetx-*. tex (used by xetex).'
complete -c mtx-chars -l pdf --description 'generate pdfr-def. tex (used by pdftex).'
complete -c mtx-chars -l entities --description 'generate entities table AUTHOR More information about ConTeXt and the tools t…'

