# mtx-metapost
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-metapost.1
complete -c mtx-metapost -l rawmp --description 'raw metapost run.'
complete -c mtx-metapost -l metafun --description 'use metafun instead of plain.'
complete -c mtx-metapost -l latex --description 'force --tex=latex.'
complete -c mtx-metapost -l texexec --description 'force texexec usage (mkii).'
complete -c mtx-metapost -l split --description 'split single result file into pages AUTHOR More information about ConTeXt and…'

