# mtx-check
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-check.1
complete -c mtx-check -l check --description 'check tex file for errors AUTHOR More information about ConTeXt and the tools…'

