# mtx-metatex
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-metatex.1
complete -c mtx-metatex -l run --description 'process (one or more) files (default action).'
complete -c mtx-metatex -l make --description 'create metatex format(s) AUTHOR More information about ConTeXt and the tools …'

