# mtx-babel
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-babel.1
complete -c mtx-babel -l language --description 'conversion language (e. g.  greek).'
complete -c mtx-babel -l structure --description 'obey given structure (e. g.  \'document\', default: \'context\').'
complete -c mtx-babel -l convert --description 'convert babel codes into utf AUTHOR More information about ConTeXt and the to…'

