# mtx-pdf
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-pdf.1
complete -c mtx-pdf -l info --description 'show some info about the given file.'
complete -c mtx-pdf -l metadata --description 'show metadata xml blob.'
complete -c mtx-pdf -l fonts --description 'show used fonts (--detail).'
complete -c mtx-pdf -l linearize --description 'linearize given file AUTHOR More information about ConTeXt and the tools that…'

