# mtx-cache
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-cache.1
complete -c mtx-cache -l purge --description 'remove not used files.'
complete -c mtx-cache -l erase --description 'completely remove cache.'
complete -c mtx-cache -l list --description 'show cache.'
complete -c mtx-cache -l all --description 'all (not yet implemented) AUTHOR More information about ConTeXt and the tools…'

