# mtx-scite
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-scite.1
complete -c mtx-scite -l words --description 'convert spell-*. txt into spell-*. lua.'
complete -c mtx-scite -l tree --description 'converts a tree into an html tree (--source --target --numbers).'
complete -c mtx-scite -l file --description 'converts a file into an html tree (--source --target --numbers --lexer) AUTHO…'

