# mtx-server
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-server.1
complete -c mtx-server -l start --description 'start server.'
complete -c mtx-server -l port --description 'port to listen to.'
complete -c mtx-server -l root --description 'server root.'
complete -c mtx-server -l scripts --description 'scripts sub path.'
complete -c mtx-server -l index --description 'index file.'
complete -c mtx-server -l auto --description 'start on own path AUTHOR More information about ConTeXt and the tools that co…'

