# mtx-flac
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-flac.1
complete -c mtx-flac -l collect --description 'collect albums in xml file.'
complete -c mtx-flac -l pattern --description 'use pattern for locating files AUTHOR More information about ConTeXt and the …'

