# mtx-epub
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-epub.1
complete -c mtx-epub -l make --description 'create epub zip file.'
complete -c mtx-epub -l purge --description 'remove obsolete files.'
complete -c mtx-epub -l rename --description 'rename images to sane names.'
complete -c mtx-epub -l svgmath --description 'convert mathml to svg.'
complete -c mtx-epub -l svgstyle --description 'use given tex style for svg generation (overloads style in specification).'
complete -c mtx-epub -l all --description 'assume: --purge --rename --svgmath (for fast testing) AUTHOR More information…'

