# mtx-profile
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-profile.1
complete -c mtx-profile -l analyze --description 'analyze lua calls.'
complete -c mtx-profile -l trace --description 'analyze tex calls AUTHOR More information about ConTeXt and the tools that co…'

