# mtx-texworks
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-texworks.1
complete -c mtx-texworks -l start --description '[--verbose]   start texworks.'
complete -c mtx-texworks -l test --description 'report what will happen AUTHOR More information about ConTeXt and the tools t…'

