# mtx-rsync
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/mtx-rsync.1
complete -c mtx-rsync -l job --description 'use given file as specification.'
complete -c mtx-rsync -l dryrun --description 'show what would happen.'
complete -c mtx-rsync -l force --description 'force run AUTHOR More information about ConTeXt and the tools that come with …'

