# musixtex
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/musixtex.1
complete -c musixtex -s v --description 'output program name and version number, and quit.'
complete -c musixtex -s h --description 'output usage summary and quit.'
complete -c musixtex -s l --description 'changes the TeX processor to  latex (1) or  pdflatex (1).'
complete -c musixtex -s p --description 'changes the TeX processor to   pdfetex (1)  or  pdflatex (1) (and doesn\'t run…'
complete -c musixtex -s d --description 'changes the dvi processor to  dvipdfm (1).'
complete -c musixtex -s s --description 'stops processing at the dvi file.'
complete -c musixtex -s g --description 'stops processing at the ps file.'
complete -c musixtex -s i --description 'retain intermediate files.'
complete -c musixtex -s 1 --description 'one-pass [pdf][la]tex processing.'
complete -c musixtex -s x --description 'call   makeindex (1) to update index database.'
complete -c musixtex -s f --description 'default processing.'
complete -c musixtex -o lx --description '.'

