# node
# Autogenerated from man page /usr/local/share/man/man1/node.1
complete -c node -l inspect --description 'Activate inspector on host:port.  Default is 127. 0. 0. 1:9229.'
complete -c node -l inspect-brk --description 'Activate inspector on host:port and break at start of user script.'
complete -c node -l inspect-port --description 'Set the host:port to be used when the inspector is activated.'
complete -c node -l pending-deprecation --description 'Emit pending deprecation warnings.'
complete -c node -l napi-modules --description 'Enable loading native modules compiled with the ABI-stable Node.'
complete -c node -l redirect-warnings --description 'Write process warnings to the given file instead of printing to stderr.'
complete -c node -l trace-events-enabled --description 'Enables the collection of trace event tracing information.'
complete -c node -l trace-event-categories --description 'A comma separated list of categories that should be traced when trace event t…'

