# ofm2opl
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/ofm2opl.1
complete -c ofm2opl -o charcode-format --description 'output character codes according to TYPE, which can be either `hex\' or `ascii…'
complete -c ofm2opl -o help --description 'display a brief summary of syntax and options .'
complete -c ofm2opl -o verbose --description 'display progress reports.'
complete -c ofm2opl -o version --description 'output version information and exit.'

