# opl2ofm
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/opl2ofm.1
complete -c opl2ofm -o help --description 'display a brief summary of syntax and options .'
complete -c opl2ofm -o verbose --description 'display progress reports.'
complete -c opl2ofm -o version --description 'output version information and exit.'

