# ovf2ovp
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/ovf2ovp.1
complete -c ovf2ovp -o charcode-format --description 'output character codes according to TYPE, which can be either `hex\' or `ascii…'
complete -c ovf2ovp -o help --description 'display a brief summary of syntax and options .'
complete -c ovf2ovp -o verbose --description 'display progress reports.'
complete -c ovf2ovp -o version --description 'output version information and exit.'

