# ovp2ovf
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/ovp2ovf.1
complete -c ovp2ovf -o help --description 'display a brief summary of syntax and options.'
complete -c ovp2ovf -o verbose --description 'display progress reports.'
complete -c ovp2ovf -o version --description 'output version information and exit.'

