# pmxchords
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/pmxchords.1
complete -c pmxchords -s v --description 'output program name and version number, and quit.'
complete -c pmxchords -s h --description 'output usage summary and quit.'
complete -c pmxchords -s s --description 'stop after first step (of producing a temporary pmx file with transposed chor…'

