# ps2pdfwr
# Autogenerated from man page /usr/local/share/man/man1/ps2pdfwr.1
complete -c ps2pdfwr -s q -o dNOPAUSE -o dBATCH -o sDEVICE --description '.'
complete -c ps2pdfwr -o dOutputFile --description 'argument, all preceded and followed by any command-line arguments.'
complete -c ps2pdfwr -o dSAFER --description 'is prepended before all the other options.'

