# psbook
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/psbook.1
complete -c psbook -s s --description 'option selects the size of signature which will be used.'
complete -c psbook -s q --description 'option suppresses this.  AUTHOR Written by Angus J.  C.  Duggan.'

