# psjoin
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/psjoin.1
complete -c psjoin -o a: --description '.'
complete -c psjoin -o s: --description '.'
complete -c psjoin -o p: --description '.'
complete -c psjoin -o h: --description '.'

