# psnup
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/psnup.1
complete -c psnup -s w --description 'option gives the paper width, and the.'
complete -c psnup -s h --description 'option gives the paper height, specified in pt , mm , cm , or in .  The .'
complete -c psnup -s p --description 'option can be used instead, to set the paper size; otherwise a default value …'
complete -c psnup -s W --description '.'
complete -c psnup -s H --description 'and.'
complete -c psnup -s P --description 'options set the input paper size, if it is different from the output size.'
complete -c psnup -s l --description 'option should be used for pages which are in landscape orientation (rotated 9…'
complete -c psnup -s r --description 'option should be used for pages which are in seascape orientation (rotated 90…'
complete -c psnup -s f --description 'option should be used for pages which have the width and height interchanged,…'
complete -c psnup -s c --description 'option changes the order to `column-major\', where successive pages are placed…'
complete -c psnup -s m --description 'option.'
complete -c psnup -s b --description 'option is used to specify an additional margin around each page on a sheet.'
complete -c psnup -s d --description 'option draws a line around the border of each page, of the specified width.'
complete -c psnup -s s --description 'option.  This is useful to merge pages which are already reduced.'
complete -c psnup -s n --description 'can also be used, for compatibility with other n-up programs.'
complete -c psnup -s q --description 'option suppresses this.'

