# psresize
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/psresize.1
complete -c psresize -s w --description 'option gives the output paper width, and the.'
complete -c psresize -s h --description 'option gives the output paper height, normally specified in cm or in to conve…'
complete -c psresize -s p --description 'option can be used instead, to set the paper size; otherwise a default value …'
complete -c psresize -s W --description 'option gives the input paper width, and the.'
complete -c psresize -s H --description 'option gives the input paper height.  The .'
complete -c psresize -s P --description 'option can be used instead, to set the paper size; otherwise a default value …'
complete -c psresize -s q --description 'option suppresses this.'

