# psselect
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/psselect.1
complete -c psselect -s e --description 'option selects all of the even pages; it may be used in conjunction with the …'
complete -c psselect -s o --description 'option selects all of the odd pages; it may be used in conjunction with the o…'
complete -c psselect -s p --description 'option specifies the pages which are to be selected.'
complete -c psselect -s r --description 'option causes psselect to output the selected pages in reverse order.'
complete -c psselect -s q --description 'option suppresses this.'

