# pstops
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/pstops.1
complete -c pstops -s w --description 'option gives the width which is used by the w dimension specifier, and the.'
complete -c pstops -s h --description 'option gives the height which is used by the h dimension specifier.'
complete -c pstops -s p --description 'option can be used as an alternative, to set the paper size.  See paper (1).'
complete -c pstops -s b --description 'option prevents any bind operators in the PostScript prolog from binding.'
complete -c pstops -s q --description 'option suppresses this.'

