# quartz-wm
# Autogenerated from man page /opt/X11/share/man/man1/quartz-wm.1
complete -c quartz-wm -l prefs-domain --description 'This option can be used to override the domain used to read preferences from.'

