# resgen
# Autogenerated from man page /usr/local/share/man/man1/resgen.1
complete -c resgen -o compile --description 'Sp This switch instructs resgen to compile multiple files.'
complete -c resgen -o usesourcepath --description '.'

