# t1ascii
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/t1ascii.1
complete -c t1ascii -l line-length -s l --description 'Set the maximum length of encrypted lines in the output to  num.'
complete -c t1ascii -l warnings -s w --description 'Warn when the input font contains lines longer than 255 characters.'

