# t1asm
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/t1asm.1
complete -c t1asm -l pfa -s a --description 'Output in PFA (ASCII) format.'
complete -c t1asm -l pfb -s b --description 'Output in PFB (binary) format.  This is the default.'
complete -c t1asm -l block-length -s l --description 'PFB only: Set the maximum output block length to  num.'
complete -c t1asm -l line-length --description 'PFA only: Set the maximum length of encrypted lines in the output to num.'

