# t1binary
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/t1binary.1
complete -c t1binary -l block-length -s l --description 'Set the maximum length of sections in PFB output to length.'

