# t1mac
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/t1mac.1
complete -c t1mac -l raw -s r --description 'Indicates that output should be a raw resource fork.'
complete -c t1mac -l macbinary --description 'Indicates that output should be in MacBinary I or II format.'
complete -c t1mac -l applesingle --description 'Indicates that output should be in AppleSingle format.'
complete -c t1mac -l appledouble --description 'Indicates that output should be in AppleDouble format.'
complete -c t1mac -l binhex --description 'Indicates that output should be in BinHex 4. 0 format.'
complete -c t1mac -l filename -s n --description 'Sets the Macintosh filename of the output font to name.'

