# texdiff
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/texdiff.1
complete -c texdiff -l nofloats -s n --description 'If given, skips contents of figure environments, but does show insertions and…'

