# texdoctk
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/texdoctk.1
complete -c texdoctk -s v --description 'verbose: enable some viewer messages which are otherwise sent to stderr, as w…'

