# texfot
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/texfot.1
complete -c texfot -l debug --description 'el.'
complete -c texfot -l no-debug --description 'el.'
complete -c texfot -l ignore --description 'el.'
complete -c texfot -l interactive --description 'el.'
complete -c texfot -l no-interactive --description 'el.'
complete -c texfot -l quiet --description 'el.'
complete -c texfot -l no-quiet --description 'el.'
complete -c texfot -l tee --description 'el.'
complete -c texfot -l version --description 'el.'
complete -c texfot -l help --description 'el.'

