# tftopl
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/tftopl.1
complete -c tftopl -o charcode-format --description 'The argument  format specifies how character codes are output in the PL file.'
complete -c tftopl -o verbose --description 'Without this option, tftopl operates silently.'

