# tie
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/tie.1
complete -c tie -s c --description 'Create a single change file from the given R changefile s.'
complete -c tie -s m --description 'Create a new master file by applying the given changefile s.'

