# ttf2afm
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/ttf2afm.1
complete -c ttf2afm -s i --description 'force printing glyph names in form `index\'decnum.'
complete -c ttf2afm -s u --description 'force printing glyph names in form `uni\'hexnum.'
complete -c ttf2afm -s c --description 'write encoding tables to file name.'
complete -c ttf2afm -s v --description 'print program version.'
complete -c ttf2afm -s e --description 'encode AFM output using encoding vector from enc.'
complete -c ttf2afm -s o --description 'output to file outfile instead of standard output.'
complete -c ttf2afm -s m --description 'PP  Platform numbers can be one of.'

