# vftovp
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/vftovp.1
complete -c vftovp -o charcode-format --description 'The argument  format specifies how character codes are output in the VPL file.'
complete -c vftovp -o verbose --description 'Without this option, vftovp operates silently.'

