# weave
# Autogenerated from man page /Library/TeX/Distributions/.DefaultTeX/Contents/Man/man1/weave.1
complete -c weave -s x --description 'says to omit the index, module name list, and table of contents pages.'

