# xmag
# Autogenerated from man page /opt/X11/share/man/man1/xmag.1
complete -c xmag -o source --description 'This option specifies the size and/or location of the source region on the sc…'
complete -c xmag -o mag --description 'This option indicates the magnification to be used.   5 is the default.'

