# xmh
# Autogenerated from man page /opt/X11/share/man/man1/xmh.1
complete -c xmh -o path --description 'This option specifies an alternate collection of mail folders in which to pro…'
complete -c xmh -o initial --description 'This option specifies an alternate folder which may receive new mail and is i…'
complete -c xmh -o flag --description 'This option will cause xmh to change the appearance of appropriate folder but…'

