# xsm
# Autogenerated from man page /opt/X11/share/man/man1/xsm.1
complete -c xsm -o display --description 'Causes xsm to connect to the specified X display.'
complete -c xsm -o session --description 'Causes xsm to load the specified session, bypassing the session menu.'
complete -c xsm -o verbose --description 'Turns on debugging information.  SETUP .'

